### ISSUE TITLE
Add markdown help component

### ISSUE THREAD

**Issue by srallen** [zooniverse/Zooniverse-React-Components#18]

**Comment by jelliotartz** [comment]
Looking at the MarkdownHelp component in Panoptes-Front-End, it looks like I'll need to import/require a few other components in order to get the modal set up in the same way it is on Panoptes-Front-End:

alert module
Dialog module
ModalFocus

My understanding of the code execution that takes place when a user clicks the question mark icon is as follows:

MarkdownHelp is called via the MarkdownEditor onHelp prop: `<MarkdownEditor ... onHelp={-> alert <MarkdownHelp/>} />`, when a user clicks the question mark icon. This calls the alert module with MarkdownHelp as its message.

Alert uses the Dialog module, which in turn uses the ModalFocus component. Should I create all of these modules and components in `Zooniverse-React-Components`, as part of this issue? Or should I keep this issue restricted to getting the MarkdownHelp component to render as a modal, and create alert, Dialog, and ModalFocus in separate issue/issues?

**Comment by srallen** [comment]
No, just add `<MarkdownHelp />` to this repository so that devs can choose if it opens in a modal and what modal library to use for the project they are working on. `<MarkdownHelp />` should just be a functional component of the help content.

**Comment by jelliotartz** [comment]
In the MarkdownHelp component in Panoptes-Front-End, the `image` and `resized image` table elements point to images stored in the public folder. Should I similarly store images in a folder in Zooniverse-React-Components? Or maybe upload images to S3, and link to them there? Or is this an issue to leave up to devs when they implement the component?

Currently, it's just rendering broken links 
![screen shot 2017-06-13 at 3 22 14 pm](https://user-images.githubusercontent.com/12473119/27102798-27b05f3e-504c-11e7-9e90-78b8b2b047fc.png)

**Comment by srallen** [comment]
Adding the simple avatar placeholder to this repository makes sense to me.

**Comment by mcbouslog** [comment]
Closing, see [Markdownz issue #57](https://github.com/zooniverse/markdownz/issues/57)
